const VECTOR_STORE = process.env.VECTOR_STORE!.toLowerCase();
const HNSWLIB_DB_DIR = process.env.HNSWLIB_DB_DIR;
const SOURCE_FILES_DIR = process.env.SOURCE_FILES_DIR;
const CHROMA_SERVER_URL = process.env.CHROMA_SERVER_URL;
const CHROMA_COLLECTION_NAME = process.env.CHROMA_COLLECTION_NAME;
const MILVUS_SERVER_URL = process.env.MILVUS_SERVER_URL;
const MILVUS_COLLECTION_NAME = process.env.MILVUS_COLLECTION_NAME;
const MILVUS_DB_USERNAME = process.env.MILVUS_DB_USERNAME;
const MILVUS_DB_PASSWORD = process.env.MILVUS_DB_PASSWORD;
const EVENT_STREAM_ENABLED = process.env.EVENT_STREAM_ENABLED !== 'false';

export { EVENT_STREAM_ENABLED, VECTOR_STORE, HNSWLIB_DB_DIR, SOURCE_FILES_DIR, CHROMA_SERVER_URL, CHROMA_COLLECTION_NAME, MILVUS_SERVER_URL, MILVUS_COLLECTION_NAME, MILVUS_DB_USERNAME, MILVUS_DB_PASSWORD };
